config:
  install_tree:
  template_dirs:
    - $spack/templates
  module_roots:
    tcl:
  build_stage:
  extensions:
  install_path_scheme: '{name}/{version}/{compiler.name}/{hash}'
  source_cache:
  misc_cache:
  build_jobs: 6
  db_lock_timeout: 20
