config:
  install_tree: /scratch/snx3000/$user/spack/install/daint #to be changed to project/c14/install/daint
  template_dirs:
    - $spack/templates
  module_roots:
    tcl:  /scratch/snx3000/$user/spack/modules
  build_stage:
    - /scratch/snx3000/$user/spack/spack-stages/daint
  install_path_scheme: '{name}/{version}/{compiler.name}/{hash}'
  source_cache: ~/.spack/source_cache
