name: Nightly tests
on:
  schedule:
    - cron: '0 0 * * *'  # Run this workflow every day at midnight
  workflow_dispatch:

jobs:
  spec-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test echo
        run: echo "Hello"