name: Nightly tests
on:
  push:
    branches:
      - update-ci
  schedule:
    - cron: '0 0 * * *'  # Run this workflow every day at midnight
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1              # --depth 1 and --shallow-submodules
          submodules: recursive       # --recurse-submodules

      - name: Create Python VENV
        run : |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Spack spec test
        run: |
          source ./setup-env.sh
          spack spec gnuconfig

      - name: Unit test
        run: |
          source .venv/bin/activate
          python3 test/unit_test.py