name: Nightly tests
on:
  push:
    branches:
      - update-ci
  schedule:
    - cron: '0 0 * * *'  # Run this workflow every day at midnight
  workflow_dispatch:

jobs:
  spec-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1              # --depth 1
          submodules: recursive       # --recurse-submodules
          submodules-fetch-depth: 1   # --shallow-submodules

      - name: Setup environment
        run: |
          echo $(pwd)
          source ./setup-env.sh
          spack spec gnuconfig